AWSTemplateFormatVersion: "2010-09-09"
Description: Launch 3 EC2 instances in an existing VPC and subnet
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 key pair for SSH access
Resources:
   Security group that allows inbound SSH from anywhere
 
 InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      VpcId: vpc-0c32d77a24c43392b
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

   Make sure the subnet is explicitly associated with the given route table
  
SubnetRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: subnet-0cc35aea439788393
      RouteTableId: rtb-05e1708fdcbcc5a88

--- EC2 instances 
  
EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0841b1152f02fa85e        
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: subnet-0cc35aea439788393
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Instance-1

EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0841b1152f02fa85e
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: subnet-0cc35aea439788393
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Instance-2

EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0841b1152f02fa85e
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: subnet-0cc35aea439788393
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Instance-3

Outputs:
  InstanceIDs:
    Description: IDs of all EC2 instances
    Value: !Join [ ",", [ !Ref EC2Instance1, !Ref EC2Instance2, !Ref EC2Instance3 ] ]
